server:
  port: ${SERVER_PORT:8082}
  max-http-request-header-size: 32KB

modulo:
  codigo: crm

spring:
  application:
    name: crm

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/plataforma}
    username: ${DB_APP_USER:usr_crm}
    password: ${DB_APP_PASSWORD:troque}

  flyway:
    user: ${DB_OWNER_USER:own_crm}
    password: ${DB_OWNER_PASSWORD:troque}
    schemas: crm
    default-schema: crm
    create-schemas: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: crm

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    virtual-host: ${RABBITMQ_VHOST:plataforma}
    username: ${RABBITMQ_USER:mq_crm}
    password: ${RABBITMQ_PASSWORD:troque}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI:http://localhost:8081/api/identity/.well-known/jwks.json}
          audiences: plataforma

logging:
  pattern:
    level: "%5p [%X{requestId:-}]"
